### PR TITLE
fix(dev): paths on windows in rspack and dev server

### LINKED ISSUE #850: Paths on Windows are not supported.
### What information was incorrect, unhelpful, or incomplete?

Paths for Windows operating systems are not recognized by the local server, which triggers an error. 

### Steps to reproduce

- OS Windows 11
- Have content (minimal) and fred folders on main HEAD
- Have made `npm install` for fred
- Have started `npm run start`
  - Issue is hidden with `npm run dev` (just return `Error occurred while trying to proxy: localhost:3000/en-US/`)

### Logs

Path to `fr/docs/Web`
```bash
[rari] serve:url:page: /fr/docs/Web req=1 /fr/docs/Web locale="fr" slug="Web" file="\\\\?\\C:\\Users\\Tristan\\Documents\\GitHub\\translated-content\\files\\fr\\web\\index.md"
[server] SSR render error: Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[server]     at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:187:11)  
[server]     at defaultLoad (node:internal/modules/esm/load:82:3)
[server]     at ModuleLoader.load (node:internal/modules/esm/loader:815:12)
[server]     at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:594:31)
[server]     at ModuleLoader.#createModuleJob (node:internal/modules/esm/loader:624:36)
[server]     at ModuleLoader.#getJobFromResolveResult (node:internal/modules/esm/loader:343:34)
[server]     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:311:41)
[server]     at processTicksAndRejections (node:internal/process/task_queues:105:5)  
[server]     at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:664:25)
[rari] serve:url:page: /fr/docs/Web req=2 /fr/docs/Web locale="fr" slug="Web" file="\\\\?\\C:\\Users\\Tristan\\Documents\\GitHub\\translated-content\\files\\fr\\web\\index.md"
[server] SSR render error: Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[server]     at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:187:11)  
[server]     at defaultLoad (node:internal/modules/esm/load:82:3)
[server]     at ModuleLoader.load (node:internal/modules/esm/loader:815:12)
[server]     at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:594:31)
[server]     at ModuleLoader.#createModuleJob (node:internal/modules/esm/loader:624:36)
[server]     at ModuleLoader.#getJobFromResolveResult (node:internal/modules/esm/loader:343:34)
[server]     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:311:41)
[server]     at processTicksAndRejections (node:internal/process/task_queues:105:5)  
[server]     at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:664:25)
```

Path to `en-US/`
```bash
[rari] serve:url:page: /en-US/ req=1 /en-US/ locale="en-US" slug="" file=""
[server] SSR render error: Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[server]     at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:187:11)  
[server]     at defaultLoad (node:internal/modules/esm/load:82:3)
[server]     at ModuleLoader.load (node:internal/modules/esm/loader:815:12)
[server]     at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:594:31)
[server]     at ModuleLoader.#createModuleJob (node:internal/modules/esm/loader:624:36)
[server]     at ModuleLoader.#getJobFromResolveResult (node:internal/modules/esm/loader:343:34)
[server]     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:311:41)
[server]     at processTicksAndRejections (node:internal/process/task_queues:105:5)  
[server]     at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:664:25)
```

### What did you expect to see?

That the paths on Windows recognize the presence of the `content` and `translated-content` (and other) folders as being on the pattern given in the `.env` file.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

- Windows 11 (LTS build)
- Node 22.20.0
- NPM 11.6.1

Current env file:

```yaml
# https://github.com/mdn/content
CONTENT_ROOT=../content/files
# https://github.com/mdn/translated-content
CONTENT_TRANSLATED_ROOT=../translated-content/files
# https://github.com/mdn/blog
# BLOG_ROOT=../blog/content/posts
# https://github.com/mdn/curriculum/
# CURRICULUM_ROOT=../curriculum
# https://github.com/mdn/mdn-contributor-spotlight
# CONTRIBUTOR_SPOTLIGHT_ROOT=../mdn-contributor-spotlight/contributors
# https://github.com/mdn/generic-content
# GENERIC_CONTENT_ROOT=../generic-content/files

RUMBA_URL="https://developer.allizom.org"
CF_URL="https://developer.allizom.org"
RARI_URL="http://localhost:8083"

# uncomment to build legacy react features
# FRED_LEGACY=true

# uncomment to enable writer mode
FRED_WRITER_MODE=true

# uncomment to enable glean
# FRED_GLEAN_ENABLED=true
# FRED_GLEAN_DEBUG=true

# legacy react-specific environment variables
REACT_APP_KUMA_HOST="localhost:3000"
REACT_APP_FXA_SIGNIN_URL="/users/fxa/login/authenticate/"
REACT_APP_FXA_SETTINGS_URL="https://accounts.stage.mozaws.net/settings/"
REACT_APP_PLACEMENT_ENABLED="true"
```

### PR DESCRIPTION
**Pull request by LeoMcA**
Fixes https://github.com/mdn/fred/issues/850

~~Need to reboot back into Linux to test it doesn't break anything there.~~ It works!

Tested across Windows 11 and Linux.

### CODE REVIEW

**Comment by tristantheb** [comment]
Looks good for `npm run start` && `npm run dev` 🙏🏻

File: build/plugins/generate-element-map.js [hunk 1]
```diff
@@ -18,14 +18,16 @@ export class GenerateElementMapPlugin {
       "GenerateElementMapPlugin",
       async () => {
         const api = new fdir()
+          .withPathSeparator("/")
           .withFullPaths()
```
Comment (caugner) [inline build/plugins/generate-element-map.js]: Could we introduce the following helper function in `build/utils.js`:

```js
export async crawl(root, filter) {
  return await new fdir()
    .withPathSeparator("/")
    .withFullPaths()
    .filter(filter)
    .crawl(root);
}
```

And if we really need `withErrors()`:


```js
export async crawl(root, filter, { withErrors = false }) {
  let api = new fdir()
    .withPathSeparator("/")
    .withFullPaths();

  if (withErrors) {
    api = api.withErrors();
  }

  return await api.filter(filter).crawl(root);
}
```

**Review by caugner — APPROVED** [review]
Looks plausible to me, didn't test on Windows.

**Comment by tristantheb** [comment]
Copy of an observation written on the issue : "If an image comes from the English repository, it is not loaded (displayed as /fr/ instead of /en-US/)."

**Comment by caugner** [comment]
> Copy of an observation written on the issue : "If an image comes from the English repository, it is not loaded (displayed as /fr/ instead of /en-US/)."

I think that's a separate issue, on production, we just redirect from `/fr/` to `/en-US/` for assets not found, and afaik that behavior has not been ported to fred's dev server yet.

File: build/plugins/generate-element-map.js (hunk 1 above)
Comment (LeoMcA) [reply build/plugins/generate-element-map.js]: Good idea: I've resorted to using [`withErrors`](https://github.com/thecodrr/fdir/blob/master/documentation.md#witherrors) everywhere, as if we have file errors in the components directory that's something we probably want to know about too

**Comment by LeoMcA** [comment]
Tested latest changes on windows again, and they work
