### PR TITLE
fix(writer-reload): add rate limiting

### LINKED ISSUE #776: Local server sometimes constantly refreshes
### What information was incorrect, unhelpful, or incomplete?

Sometimes the local server seems to be constantly reloading the page. It's really distracting.

### What did you expect to see?

The local server not to be constantly reloading the page.

### Do you have any supporting links, references, or citations?

Image

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by LeoMcA**
Fixes https://github.com/mdn/fred/issues/776

Adds an exponential back-off to reloads if the first comparison each page load is different.

### CODE REVIEW

File: components/writer-reload/element.js [hunk 1]
```diff
@@ -26,22 +44,33 @@ export default class MDNWriterReload extends LitElement {
     const res = await fetch(url);
     if (res.ok) {
       const state = await res.text();
+      // eslint-disable-next-line unicorn/no-negated-condition
```
Comment (LeoMcA) [inline components/writer-reload/element.js:47]: Opted to override eslint here and below because I think this order makes more sense - it follows the ordering of operations.

**Review by argl — APPROVED** [review]
