### PR TITLE
fix(interactive-example): add title to Run/Reset + console

### LINKED ISSUE #520: Playground ‘run’ doesn’t announce
There's no feedback after clicking ‘Run’ in live samples

### PR DESCRIPTION
**Pull request by caugner**
### Description

1. Adds `title` to the <kbd>Run</kbd> / <kbd>Reset</kbd> buttons on interactive examples, and to the console output.
2. Makes the console output lines tabbable.

### Motivation

Improve accessibility.

### Additional details

PS: I tried to use `aria-controls`, but it had no observable effect to me with VoiceOver.

### Related issues and pull requests

Fixes https://github.com/mdn/fred/issues/520.

### CODE REVIEW

File: components/interactive-example/with-console.js [hunk 1]
```diff
@@ -47,15 +47,27 @@ export const InteractiveExampleWithConsole = (Base) =>
...
                 >${this.l10n`Reset`}</mdn-button
               >
             </div>
-            <mdn-play-console id="console"></mdn-play-console>
+            <mdn-play-console
+              id="console"
+              title=${this.l10n`Console output`}
+            ></mdn-play-console>
             <mdn-play-runner
+              id="runner"
```
Comment (caugner) [inline components/interactive-example/with-console.js]:
```suggestion
```

File: components/play-console/element.css [hunk 2]
```diff
@@ -25,7 +25,7 @@ li {
   padding: 0 0.5em;
 
   &::before {
-    content: ">";
+    content: "> ";
```
Comment (caugner) [inline components/play-console/element.css:28]: Note: This is a tiny improvement that avoids selecting a console log message has a trailing space.

**Review by argl — APPROVED** [review]
Nice!
