### PR TITLE
fix(site-search): add divider between result preview snippets

### LINKED ISSUE #859: Broken summary for CORS
### Proposal

I am not sure what is going on here but something is getting stitched together incorrectly.

Image

### PR DESCRIPTION
**Pull request by argl**
### Description

Fixes the assembly of resutl highlight snippets with a divider.

### Motivation

Assembly was broken with missing whitespace

### Additional details

image

### Related issues and pull requests

Fixes #859

### CODE REVIEW

File: components/site-search/element.js [hunk 1]
```diff
@@ -361,7 +361,11 @@ export class MDNSiteSearch extends L10nMixin(LitElement) {
                         <p class="site-search-results__description">
                           ${result.highlight.body &&
                           result.highlight.body.length > 0
-                            ? result.highlight.body.map((b) => unsafeHTML(b))
+                            ? result.highlight.body.flatMap((b, i) =>
+                                i === 0
+                                  ? [unsafeHTML(b)]
+                                  : [html` … `, unsafeHTML(b)],
+                              )
```
Comment (caugner) [inline components/site-search/element.js]: I think it would be cleaner to use Lit's [`join` directive](https://lit.dev/docs/templates/directives/#join):

```suggestion
                            ? join(result.highlight.body.map((b) => unsafeHTML(b)), html` … `),
                              )
```

File: components/site-search/element.css [hunk 2]
```diff
@@ -209,6 +209,10 @@
     color: inherit;
     background-color: var(--color-highlight-background);
   }
+
+  .divider {
+    color: var(--color-text-secondary);
+  }
```
Comment (caugner) [inline components/site-search/element.css:215]: This doesn't seem to be used. Leftover from an earlier version?

```suggestion
```

**Review by caugner — CHANGES_REQUESTED** [review]

File: components/site-search/element.css (hunk 2 above)
Comment (argl) [reply components/site-search/element.css:215]: Not a leftover but a half-done styling clue. See latest version.

**Review by caugner — APPROVED** [review]

File: components/site-search/element.js [hunk 3]
```diff
@@ -361,7 +362,10 @@ export class MDNSiteSearch extends L10nMixin(LitElement) {
                         <p class="site-search-results__description">
                           ${result.highlight.body &&
                           result.highlight.body.length > 0
-                            ? result.highlight.body.map((b) => unsafeHTML(b))
+                            ? join(
+                                result.highlight.body.map((b) => unsafeHTML(b)),
+                                html`<span class="divider"> … </span>`,
```
Comment (caugner) [inline components/site-search/element.js:367]: Note: An alternative would be to render this as an actual list, and add the divider with CSS. But I'm not sure how much better this really would be from the point of view of a screen reader.

Comment (argl) [reply components/site-search/element.js:367]: Thought about that, but bending lists into the current design seems moot, and the joining with n-1 dividers seems cumbersome with lists. I think the current approach is as sound as it can be, without rethinking the results design.
