### PR TITLE
fix(search-modal): support adding from context menu in Firefox

### LINKED ISSUE #619: Search field can no longer be added to Firefox from context menu
### What information was incorrect, unhelpful, or incomplete?

The context menu entry for this is gone:

Image

### What did you expect to see?

This is what it looks like on Wikipedia where it still works:

Image

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by LeoMcA**
Fixes https://github.com/mdn/fred/issues/619

### CODE REVIEW

File: components/search-modal/element.js [hunk 1]
```diff
@@ -215,9 +215,15 @@ export class MDNSearchModal extends L10nMixin(LitElement) {
     const siteSearchIndex = this._queryIndex.value?.length || 0;
     return html`
       <dialog @keydown=${this._keydown} @focusin=${this._focus} closedby="any">
-        <form @submit=${this._submit}>
+        <form
+          @submit=${this._submit}
+          method="get"
+          action=${`/${this.locale}/search`}
```
Comment (caugner) [inline components/search-modal/element.js]: Nit: I'd expect event handlers to go last.

```suggestion
          method="get"
          action=${`/${this.locale}/search`}
          @submit=${this._submit}
```

File: components/search-modal/element.js [hunk 2]
```diff
@@ -215,9 +215,15 @@ export class MDNSearchModal extends L10nMixin(LitElement) {
...
+        >
           <input
-            type="text"
+            type="search"
+            name="q"
+            title="MDN Web Docs"
```
Comment (caugner) [inline components/search-modal/element.js]: Nit: Localize.

```suggestion
            title=${this.l10n`MDN Web Docs`}
```

**Review by caugner — APPROVED** [review]
Nit: I'd consider this a `fix`.
