### PR TITLE
fix(live-sample-result): use code hash as subdomain

### LINKED ISSUE #724: LiveSampleLink macro links point to HTTP 403
STR:

1. Go to https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth#result
2. Click on _view the results of the demo code in a separate page_.

Expected: Interstitial asking user to confirm.

Actual: HTTP 403 error page.

(Similar to https://github.com/mdn/fred/issues/697, but not the same.)

### PR DESCRIPTION
**Pull request by caugner**
### Description

- Adds `permalink` option to the `play-runner` component.
- Uses this option in the `live-sample-result` component.

### Motivation

Ensures the runner URL can be opened in a new tab, without yielding a HTTP 403.

### Additional details

Compare

- https://fred-pr922.review.mdn.allizom.net/en-US/docs/Web/API/Window/innerWidth#result
- https://fred.review.mdn.allizom.net/en-US/docs/Web/API/Window/innerWidth#result

### Related issues and pull requests

Fixes #724.

### CODE REVIEW

**Comment by caugner** [comment]
@LeoMcA Do you know what might cause the error `private names aren't valid in this context`?

**Comment by LeoMcA** [comment]
@caugner yes, it appears to come from [this example](https://fred-pr922.review.mdn.allizom.net/en-US/docs/MDN/Kitchensink#rect_code) and bad escaping, you'll see the JS example contains lines like `if (rect1.x > rect2.x + rect2.w &#x26;&#x26;` with `&` escaped to `&#x26` - it's weird that this only occurs in the test in this PR though, considering it's also visible [on prod](https://developer.mozilla.org/en-US/docs/MDN/Kitchensink#rect_code) - perhaps something about our test environment wasn't allowing these examples to run prior to this change

File: components/play-runner/element.js [hunk 1]
```diff
@@ -48,7 +49,12 @@ export class MDNPlayRunner extends LitElement {
     this.allow = undefined;
     /** @type {string | undefined} */
     this.sandbox = undefined;
-    this._subdomain = crypto.randomUUID();
+    /** @type {boolean} */
+    this.permalink = false;
+    /** @type {string} */
+    this._hash = crypto.randomUUID();
```
Comment (LeoMcA) [inline components/play-runner/element.js]: This isn't the hash, so the naming's a bit confused, perhaps:
```suggestion
    this._uuid = crypto.randomUUID();
```
or simply keep:
```suggestion
    this._subdomain = crypto.randomUUID();
```
and conditionally overwrite it later

File: components/play-runner/element.js [hunk 2]
```diff
@@ -102,7 +109,7 @@ export class MDNPlayRunner extends LitElement {
       );
       const prefix = (srcPrefix || "").replace(/\/$/, "");
       signal.throwIfAborted();
-      // We're using a random subdomain for origin isolation.
+      this._subdomain = permalink ? hash : this._hash;
```
Comment (LeoMcA) [inline components/play-runner/element.js]: Though I *do* like the replacement of this comment with actual code, so perhaps:

```suggestion
      const subdomain = permalink ? hash : this._uuid;
```

Comment (caugner) [reply components/play-runner/element.js]: So we need to remember the current subdomain in order to only handle messages from that host.

Furthermore, if we were to toggle `permanent` on and then off (unlikely but possible), then the current implementation would use the same subdomain before and after.

I had first implemented the random yet stable subdomain as the opt-in behaviour, assuming this is only needed for CSS choice examples possibly to support the transition, but then inverted the property to keep this scoped to fix the issue.

**Comment by caugner** [comment]
> @caugner yes, it appears to come from [this example](https://fred-pr922.review.mdn.allizom.net/en-US/docs/MDN/Kitchensink#rect_code) and bad escaping, you'll see the JS example contains lines like `if (rect1.x > rect2.x + rect2.w &#x26;&#x26;` with `&` escaped to `&#x26` - it's weird that this only occurs in the test in this PR though, considering it's also visible [on prod](https://developer.mozilla.org/en-US/docs/MDN/Kitchensink#rect_code) - perhaps something about our test environment wasn't allowing these examples to run prior to this change

@LeoMcA Thanks, good catch, I opened https://github.com/mdn/content/pull/41559.

File: components/play-runner/element.js (hunk 2 above)
Comment (LeoMcA) [reply components/play-runner/element.js]: > So we need to remember the current subdomain in order to only handle messages from that host.

So we do! I had ctrl-clicked on `this._subdomain` expecting it to give me the references, but it gave me the definitions.
